package edu.wvfs.fsu.v89mobileradio;


public class ScheduleData{
	public static String[] ProgramTitle = {"SUNDAY MORNING BLUES", "LEGACIES", "WORLD MUSIC SHOW",
		"SUNDAY EVENING JAZZ", "SOLAMENTE LATINO", "ARTIST FEATURE", "STARING AT THE SUN", "YOUR VOICE",
		"TOMAHAWK TALK", "NEW RELEASE", "HOOTENANNY", "45 SPEED", "BETTER OFF DEAD", "SONIC SAFARI",
		"ORTHOPHONIA", "VOX POULI", "THE VOICE BOX", "SONIC SAFARI HONKY TALK", "MICKEE FAUST CABARET", 
		"METAL MADNESS", "CLUB CONVERGE", "TOP 10 AT 10", "FRIDAY NITE ALL-REQUEST", "TIME MACHINE", 
		"VIBES HOUSE REGGAE JAM", "UNDAGROUND RAILROAD", "SATURDAY NIGHT FISH FRY", "SATURDAY NIGHT PARTY", 
		"CAFFEINE-A-GO-GO", "12-O'CLOCK TAKEOVER", "NEWS & SPORTS", "WEATHER UPDATE", "CONCERT UPDATE"};
	public static String[] ProgramDescription = {"BLUES, R & B and GOSPEL", "SINGER/SONGWRITER",
		"FROM AROUND THE GLOBE", "NEW and TRADITIONAL JAZZ\nLIVE the 1st Sunday of the Month", 
		"SALSA, FLAMEANCO, MARIACHI, and MORE!", "ARTIST/BAND/LABEL RETROSPECTIVE", "EXPERIMENTAL MUSIC",
		"NEWS CALL-IN SHOW", "SPORTS CALL-IN SHOW", "NEW RELEASE PROGRAM", "LOCAL MUSIC / INTERVIEWS / LIVE STUDIO PERFORMANCES",
		"INDIE LABEL 7 INCHES", "PUNK, PURE PUNK", "AUDITORY SCHMORGASBORG", "Music from the world of scratchy sounds", 
		"NEWS MAGAZINE", "LITERATURE/SPOKEN WORD", "HOUR OF OLD SCHOOL COUNTRY, ROCKABILLY and MORE!",
		"The Fifth of Faust Comedy Hour POLITICAL/SOCIAL SATIRE", "METAL AND HARDCORE", "DANCE MUSIC AND MORE!", 
		"V89'S WEEKLY TOP 10", "YOU CALL THE SHOTS", "10 YEARS OR OLDER", "MUSIC OF THE ISLANDS", 
		"NEW AND OLD SCHOOL HIP - HOP", "CLASSIC and OBSCURE SOUL and R & B from the 60s, 70s, and 80s",
		"ALL REQUEST", "MUSIC TO GET YOU GOING!", "LISTENER SHOWCASE", "WORLD/STATE/LOCAL", "LOCAL FORECAST",
		"ALL YOU NEED TO KNOW"};
	
	//ArrayList <String> al = new ArrayList <String>();

}
